pipeline {
    agent any

    stages {
        stage('Dependencies') {
            steps {
                sh 'cd JSPaint && npm i && npm ci'
            }
        }
        stage('Build') {
            steps {
                sh 'cd JSPaint && npm run test:start-server'
            }
        }
        stage('Test') {
            steps {
                sh 'cd JSPaint && npm test && npm run accept'
            }  
        }

    }
}
