pipeline {
    agent any

    stages {
        stage('Dependencies') {
            steps {
                sh 'cd JSPaint && npm i'
            }
        }
        stage('Build') {
            steps {
                sh 'npm start'
            }
        }
        stage('Test') {
            steps {
                sh 'npm test'
                sh 'npm run accept'
            }  
        }

    }
}
